assignment3: assignment3.o ShelterBST.o
	g++ -o assignment3 assignment3.o ShelterBST.o

assignment3.o: assignment3.cpp ShelterBST.h
	g++ -c -Wall -Werror -pedantic -std=c++11 assignment3.cpp

ShelterBST.o: ShelterBST.cpp ShelterBST.h
	g++ -c -Wall -Werror -pedantic -std=c++11 ShelterBST.cpp